# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{grb}
  s.version = "0.4.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jinzhu Zhang"]
  s.date = %q{2011-04-07}
  s.default_executable = %q{grb}
  s.description = %q{A tool to simplify working with remote branches}
  s.email = %q{wosmvp@gmail.com}
  s.executables = ["grb"]
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "VERSION",
    "lib/grb.rb"
  ]
  s.homepage = %q{http://github.com/jinzhu/grb}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.4.2}
  s.summary = %q{A tool to simplify working with remote branches}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

